/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author ANDRES
 */
public class VistaCliente extends javax.swing.JPanel {

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblNombreCliente = new javax.swing.JLabel();
        lblTipoCliente = new javax.swing.JLabel();
        lblNumeroDocumentoTxt = new javax.swing.JLabel();
        lblNumeroDocumento = new javax.swing.JLabel();
        lblFechaNacimientoTxt = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblEmailTxt = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblNombreCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombreCliente.setText("Nombre cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 25, 0, 0);
        add(lblNombreCliente, gridBagConstraints);

        lblTipoCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblTipoCliente.setForeground(new java.awt.Color(102, 102, 102));
        lblTipoCliente.setText("Tipo de cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 5, 0);
        add(lblTipoCliente, gridBagConstraints);

        lblNumeroDocumentoTxt.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNumeroDocumentoTxt.setText("N° Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 25, 3, 0);
        add(lblNumeroDocumentoTxt, gridBagConstraints);

        lblNumeroDocumento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNumeroDocumento.setText("numero_documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(lblNumeroDocumento, gridBagConstraints);

        lblFechaNacimientoTxt.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblFechaNacimientoTxt.setText("Fecha nacimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 25, 3, 0);
        add(lblFechaNacimientoTxt, gridBagConstraints);

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblFechaNacimiento.setText("fecha_nacimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(lblFechaNacimiento, gridBagConstraints);

        lblEmailTxt.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblEmailTxt.setText("E - mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 25, 3, 0);
        add(lblEmailTxt, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblEmail.setText("email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(lblEmail, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(btnModificar, gridBagConstraints);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(btnEliminar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 25);
        add(jPanel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailTxt;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFechaNacimientoTxt;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblNumeroDocumento;
    private javax.swing.JLabel lblNumeroDocumentoTxt;
    private javax.swing.JLabel lblTipoCliente;
    // End of variables declaration//GEN-END:variables
}
